name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - staging

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  APP_NAME: ${{ secrets.STAGING_APP_NAME }}
  REGION: us-west1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .secret folder
        run: mkdir .secret

      - name: Create Credential JSON
        id: create-json-1
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "pmc-portal-credential.json"
          json: ${{ secrets.GCLOUD_AUTH }}
          dir: ".secret/"

      - name: Create env file
        run: |
          touch .env
          echo ORIGIN=${{ secrets.STAGING_ORIGIN }} >> .env
          echo BUCKET_NAME=${{ secrets.BUCKET_NAME }} >> .env
          echo STRIPE_SECRET=${{ secrets.STRIPE_TEST_SECRET }} >> .env
          echo FIRESTORE_DATABASE_ID=${{ secrets.FIRESTORE_STAGING_DATABASE_ID }} >> .env
          echo PMC_EMAIL_SENDER=${{ secrets.PMC_EMAIL_SENDER }} >> .env
          echo PMC_EMAIL_LOGIN=${{ secrets.PMC_EMAIL_LOGIN }} >> .env
          echo PMC_EMAIL_PWD="${{ secrets.PMC_EMAIL_PWD }}" >> .env

      - name: Log into Google Cloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Run Cloud Build
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}

      - name: Deploy to Cloud Run
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}
<<<<<<< HEAD
<<<<<<< HEAD
          gcloud run deploy ${{ env.APP_NAME }} --image gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }} --region ${{ env.REGION }} --allow-unauthenticated
=======
<<<<<<< HEAD
          gcloud run deploy ${{ env.APP_NAME }} --image gcr.io/${{ env.PROJECT_ID }}/${{ env.APP_NAME }} --region ${{ env.REGION }} --allow-unauthenticated --set-env-vars $(cat .env | tr '\n' ',' | sed 's/,$//')
=======
          gcloud run deploy ${{ env.STAGING_APP_NAME }} --image gcr.io/${{ env.PROJECT_ID }}/${{ env.STAGING_APP_NAME }} --region ${{ env.REGION }} --allow-unauthenticated --set-env-vars $(cat .env | tr '\n' ',' | sed 's/,$//')
>>>>>>> bc4ff24 (created new staging workflow)
>>>>>>> 90da1d2 (created new staging workflow)
=======
          gcloud run deploy ${{ env.STAGING_APP_NAME }} --image gcr.io/${{ env.PROJECT_ID }}/${{ env.STAGING_APP_NAME }} --region ${{ env.REGION }} --allow-unauthenticated --set-env-vars $(cat .env | tr '\n' ',' | sed 's/,$//')
>>>>>>> b1bb425 (Implemented event registration confirmation email (#31))
